import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
/**
 * Old data, new fields.
 *
 * Every store this repo has predates Phase 2, and the real installs are full of
 * rows written before `projectId`, `commitSha`, `promptFile` and
 * `consequenceTaskIds` existed. None of those fields may be load-bearing on
 * read: an old row has to come back through the API unchanged and unbroken,
 * with the new keys simply absent.
 *
 * Fixtures below are deliberately written in the OLD shape by hand rather than
 * produced by today's writers — a fixture generated by current code would drift
 * into the new shape and stop testing anything.
 */
import { afterAll, describe, expect, it } from 'vitest';

const dataDir = mkdtempSync(path.join(os.tmpdir(), 'ligma-migration-p2-'));
process.env.LIGMA_DATA_DIR = dataDir;

// Pre-Phase-2 activity log: no `projectId` on any row.
writeFileSync(
  path.join(dataDir, 'activity-log.json'),
  JSON.stringify({
    events: [
      {
        id: 'evt_old_1',
        type: 'task_created',
        actor: 'system',
        taskId: 'task_1',
        summary: 'Task created: Wire the button',
        details: '',
        timestamp: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'evt_old_2',
        type: 'decision_answered',
        actor: 'me',
        taskId: null,
        summary: 'Answered: ship it?',
        details: 'decision:dec_1',
        timestamp: '2026-01-02T00:00:00.000Z',
      },
    ],
  }),
  'utf-8',
);

// Pre-Phase-2 runs: no commitSha, promptFile or changesFile.
writeFileSync(
  path.join(dataDir, 'active-runs.json'),
  JSON.stringify({
    runs: [
      {
        id: 'run_old_1',
        taskId: 'task_1',
        agentId: 'developer',
        projectId: 'proj_1',
        pid: 0,
        status: 'completed',
        startedAt: '2026-01-01T00:00:00.000Z',
        completedAt: '2026-01-01T00:20:00.000Z',
        exitCode: 0,
        error: null,
        outputFile: null,
      },
    ],
  }),
  'utf-8',
);

// Pre-Phase-2 decisions: no consequenceTaskIds.
writeFileSync(
  path.join(dataDir, 'decisions.json'),
  JSON.stringify({
    decisions: [
      {
        id: 'dec_old_1',
        requestedBy: 'system',
        taskId: 'task_1',
        question: 'Ship it?',
        options: ['yes', 'no'],
        context: '',
        status: 'answered',
        answer: 'yes',
        answeredAt: '2026-01-02T00:00:00.000Z',
        createdAt: '2026-01-01T00:00:00.000Z',
      },
    ],
  }),
  'utf-8',
);

writeFileSync(
  path.join(dataDir, 'tasks.json'),
  JSON.stringify({
    tasks: [
      {
        id: 'task_1',
        title: 'Wire the button',
        projectId: 'proj_1',
        kanban: 'done',
        deletedAt: null,
      },
    ],
  }),
  'utf-8',
);

const activityLog = await import('../routes/activity-log/route');
const runs = await import('../routes/runs/route');
const decisions = await import('../routes/decisions/route');
const { activityEventCreateSchema, decisionUpdateSchema } = await import('./validations');

afterAll(() => {
  rmSync(dataDir, { recursive: true, force: true });
});

describe('an activity log written before projectId existed', () => {
  it('loads and serves without error', async () => {
    const res = await activityLog.GET(new Request('http://x/api/activity-log'));
    expect(res.status).toBe(200);
    const { events } = (await res.json()) as { events: Array<Record<string, unknown>> };
    expect(events).toHaveLength(2);
  });

  it('leaves projectId absent rather than inventing one', async () => {
    const res = await activityLog.GET(new Request('http://x/api/activity-log'));
    const { events } = (await res.json()) as { events: Array<Record<string, unknown>> };
    // Absent, not null and certainly not backfilled by joining through tasks:
    // a row that never recorded a project does not know one, and guessing would
    // put a fact on the timeline that nothing witnessed.
    for (const event of events) expect(event).not.toHaveProperty('projectId');
  });

  it('still accepts a new-format event, and still accepts one without projectId', () => {
    const base = { type: 'run' as const, summary: 'Run started', taskId: 'task_1' };
    expect(activityEventCreateSchema.safeParse({ ...base, projectId: 'proj_1' }).success).toBe(
      true,
    );
    expect(activityEventCreateSchema.safeParse({ ...base, projectId: null }).success).toBe(true);
    expect(activityEventCreateSchema.safeParse(base).success).toBe(true);
    // And the omission survives validation as an omission.
    const parsed = activityEventCreateSchema.parse(base);
    expect(parsed).not.toHaveProperty('projectId');
  });

  it('accepts all four new event kinds', () => {
    for (const type of ['run', 'verdict', 'promote', 'design_turn'] as const) {
      expect(activityEventCreateSchema.safeParse({ type, summary: `a ${type}` }).success).toBe(
        true,
      );
    }
  });
});

describe('run rows written before commitSha existed', () => {
  it('serve through GET /api/runs', async () => {
    const res = await runs.GET();
    expect(res.status).toBe(200);
    const body = (await res.json()) as { runs: Array<Record<string, unknown>> };
    const old = body.runs.find((r) => r.id === 'run_old_1');
    expect(old).toBeDefined();
    expect(old!.status).toBe('completed');
    expect(old).not.toHaveProperty('commitSha');
    expect(old).not.toHaveProperty('promptFile');
    expect(old).not.toHaveProperty('changesFile');
  });
});

describe('decisions written before consequenceTaskIds existed', () => {
  it('load and serve without error', async () => {
    const res = await decisions.GET(new Request('http://x/api/decisions'));
    expect(res.status).toBe(200);
    const body = (await res.json()) as { decisions: Array<Record<string, unknown>> };
    expect(body.decisions[0].id).toBe('dec_old_1');
    expect(body.decisions[0]).not.toHaveProperty('consequenceTaskIds');
  });

  it('validate as updates with or without the new field', () => {
    expect(decisionUpdateSchema.safeParse({ id: 'dec_old_1', answer: 'yes' }).success).toBe(true);
    expect(
      decisionUpdateSchema.safeParse({
        id: 'dec_old_1',
        answer: 'yes',
        consequenceTaskIds: ['task_1'],
      }).success,
    ).toBe(true);
    // `[]` is meaningful — "applied, and it changed nothing" — so it must pass.
    expect(
      decisionUpdateSchema.safeParse({ id: 'dec_old_1', consequenceTaskIds: [] }).success,
    ).toBe(true);
  });
});

describe('a store file that does not exist at all', () => {
  it('is still an empty log, not an error (readOrDefault)', async () => {
    rmSync(path.join(dataDir, 'activity-log.json'));
    const res = await activityLog.GET(new Request('http://x/api/activity-log'));
    expect(res.status).toBe(200);
    expect(((await res.json()) as { events: unknown[] }).events).toEqual([]);
  });
});
