import type { ExportResult } from './index';

const TAILWIND_CDN = 'https://cdn.tailwindcss.com';
const TAILWIND_TAG = `<script src="${TAILWIND_CDN}"></script>`;

export interface ExportHtmlOptions {
  /** Inject the Tailwind CDN script if missing. Defaults to true. */
  injectTailwind?: boolean;
  /** Prettify with two-space indentation. Defaults to true. */
  prettify?: boolean;
  /** Comment banner injected at the top of the file. */
  bannerComment?: string;
}

/**
 * Export an HTML artifact to disk as a single self-contained file.
 *
 * Tier 1 inlines what we can do without parsing the DOM: the Tailwind CDN
 * tag, a doctype, a viewport meta, and a small comment banner. Anything that
 * needs a real HTML parser (font subsetting, SVG inlining, JS bundling) waits
 * for Tier 2 — and is loud about it: never silently skip work the caller
 * believed we did.
 */
export async function exportHtml(
  htmlContent: string,
  destinationPath: string,
  opts: ExportHtmlOptions = {},
): Promise<ExportResult> {
  const fs = await import('node:fs/promises');
  const final = buildHtmlDocument(htmlContent, opts);
  await fs.writeFile(destinationPath, final, 'utf8');
  const stat = await fs.stat(destinationPath);
  return { bytes: stat.size, path: destinationPath };
}

export function buildHtmlDocument(htmlContent: string, opts: ExportHtmlOptions = {}): string {
  const injectTailwind = opts.injectTailwind ?? true;
  const prettify = opts.prettify ?? true;
  const banner = opts.bannerComment ?? 'Generated by ligma — https://github.com/alexraymond/ligma';

  let out = ensureDocumentShell(htmlContent);
  if (injectTailwind && !hasTailwindScript(out)) {
    out = injectIntoHead(out, TAILWIND_TAG);
  }
  out = injectIntoHead(out, `<meta name="generator" content="ligma" />`);
  out = `<!-- ${banner} -->\n${out}`;
  if (prettify) out = prettifyHtml(out);
  return out;
}

function ensureDocumentShell(html: string): string {
  const trimmed = html.trim();
  if (/^<!doctype/i.test(trimmed)) return trimmed;
  if (/<html[\s>]/i.test(trimmed)) return `<!doctype html>\n${trimmed}`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>ligma export</title>
</head>
<body>
${trimmed}
</body>
</html>`;
}

function hasTailwindScript(html: string): boolean {
  return /cdn\.tailwindcss\.com/i.test(html);
}

function injectIntoHead(html: string, tag: string): string {
  if (/<head[\s>]/i.test(html)) {
    return html.replace(/<head([^>]*)>/i, (m) => `${m}\n  ${tag}`);
  }
  if (/<html[^>]*>/i.test(html)) {
    return html.replace(/<html([^>]*)>/i, (m) => `${m}\n<head>\n  ${tag}\n</head>`);
  }
  return `${tag}\n${html}`;
}

/**
 * Raw-text elements: everything between the open and close tag is character
 * data, not markup. Collapsing whitespace or inserting newlines in here breaks
 * the document — a newline landing inside a JS string literal is a SyntaxError,
 * and `<pre>` whitespace is the content.
 */
const RAW_TEXT_ELEMENTS = ['script', 'style', 'pre', 'textarea'] as const;
const RAW_TEXT_RE = new RegExp(
  `<(${RAW_TEXT_ELEMENTS.join('|')})(\\s[^>]*)?>([\\s\\S]*?)</\\1\\s*>`,
  'gi',
);
// Private-use codepoints: cannot appear in the `>`/`<`/whitespace classes the
// tokenizer splits on, and are not produced by any transform below.
const RAW_OPEN = '\uE000';
const RAW_CLOSE = '\uE001';

/**
 * Replace the *contents* of every raw-text element with an index placeholder so
 * the whitespace transforms below can never reach inside them. Returns the
 * masked document plus the bodies to splice back afterwards.
 */
function maskRawText(html: string): { masked: string; bodies: string[] } {
  const bodies: string[] = [];
  const masked = html.replace(
    RAW_TEXT_RE,
    (_m, tag: string, attrs: string | undefined, body: string) => {
      const index = bodies.push(body) - 1;
      return `<${tag}${attrs ?? ''}>${RAW_OPEN}${index}${RAW_CLOSE}</${tag}>`;
    },
  );
  return { masked, bodies };
}

function unmaskRawText(html: string, bodies: string[]): string {
  return html.replace(
    new RegExp(`${RAW_OPEN}(\\d+)${RAW_CLOSE}`, 'g'),
    (whole, index: string) => bodies[Number(index)] ?? whole,
  );
}

/**
 * Indentation-only prettifier. Splits inline tags onto fresh lines and
 * reflows indentation. We deliberately avoid pulling in `prettier` /
 * `js-beautify` (would blow the dep budget) — Tier 2 can swap this out.
 *
 * ponytail: significant whitespace *between* inline elements (`<b>a</b> <b>b</b>`)
 * is still collapsed — separating that from insignificant inter-block whitespace
 * needs a real HTML parser, which is the Tier 2 swap above.
 */
function prettifyHtml(html: string): string {
  const { masked, bodies } = maskRawText(html);
  const tokens = masked.replace(/>\s+</g, '><').replace(/></g, '>\n<').split('\n');

  const voidElements = new Set([
    'area',
    'base',
    'br',
    'col',
    'embed',
    'hr',
    'img',
    'input',
    'link',
    'meta',
    'param',
    'source',
    'track',
    'wbr',
  ]);
  // Only reachable for an *unterminated* raw-text element (maskRawText already
  // collapsed every well-formed one onto a single token) — kept so malformed
  // input degrades the way it always did instead of exploding.
  const inline = new Set<string>(RAW_TEXT_ELEMENTS);

  let depth = 0;
  let inInline: string | null = null;
  const lines: string[] = [];

  for (const raw of tokens) {
    const line = raw.trim();
    if (!line) continue;

    if (inInline) {
      lines.push(line);
      if (new RegExp(`</${inInline}\\s*>`, 'i').test(line)) {
        inInline = null;
        depth = Math.max(0, depth - 1);
      }
      continue;
    }

    const closing = /^<\//.test(line);
    const selfClosing = /\/>\s*$/.test(line) || isVoidTag(line, voidElements);
    const isComment = /^<!--/.test(line);
    const isDoctype = /^<!doctype/i.test(line);

    if (closing) depth = Math.max(0, depth - 1);

    lines.push(`${'  '.repeat(depth)}${line}`);

    const tagName = openTagName(line);
    if (tagName && inline.has(tagName) && !selfClosing) {
      const sameLine = new RegExp(`</${tagName}\\s*>`, 'i').test(line);
      if (!sameLine) {
        inInline = tagName;
        depth += 1;
      }
      continue;
    }

    if (!closing && !selfClosing && !isComment && !isDoctype && tagName) {
      depth += 1;
    }
  }

  return `${unmaskRawText(lines.join('\n'), bodies)}\n`;
}

function openTagName(line: string): string | null {
  const m = /^<([a-zA-Z][a-zA-Z0-9-]*)/.exec(line);
  return m ? (m[1] as string).toLowerCase() : null;
}

function isVoidTag(line: string, voids: Set<string>): boolean {
  const name = openTagName(line);
  return name !== null && voids.has(name);
}
